


# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 03:22

from __future__ import unicode_literals

from django.db import migrations

from movie_lens_online.models import Rater,  Movie,  Rating

from django.apps import apps

def get_movie_names(apps, schema_editor):

    Rating = apps.get_model("movie_lens_online", "Rating")
    Movie = apps.get_model("movie_lens_online", "Movie")

    #rating_rows = len(Rating.objects.all())
    counter = 0

    for sgl_Movie_row in Movie.objects.values().order_by('movie_id'):

        while counter <= 99999:


            rating_row_obj= Rating(**Rating.objects.values().order_by('movie_id')[counter])

            if rating_row_obj.movie_id != sgl_Movie_row['movie_id']:

                break

            else:

                rating_row_obj.movie_name = sgl_Movie_row['movie_title']

                rating_row_obj.save()

                counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0009_auto_20160508_0318'),
    ]

    operations = [
        migrations.RunPython(get_movie_names)
    ]
