# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 01:40

from __future__ import unicode_literals
from django.db import migrations
import csv
from movie_lens_online.models import Rater

#Rater.objects.all().delete()

def import_raters(apps, schema_editor):
    Rater = apps.get_model("movie_lens_online", "Rater")

    with open ('/Users/Pipita/movie_lenses/Data/u.user') as user_file:

        user_dataset = csv.DictReader(user_file, fieldnames=('user_id', 'age', 'sex','occupation',  ""), delimiter="|") # 'zip_code',

        for row in user_dataset:
            rater = Rater(user_id=row['user_id'], age=row['age'], sex=row['sex'], occupation=row['occupation']) #zip_code=row['zip_code']
            rater.save()



class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0003_auto_20160505_2018'),
    ]

    operations = [
        migrations.RunPython(import_raters)
    ]
