# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_lens_online', '0007_auto_20160506_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='auth_u',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
