# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0007_auto_20160506_0437'),
    ]

    operations = [
    ]
