# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 02:18
from __future__ import unicode_literals

from django.db import migrations
import csv
from django.utils import timezone
import datetime

from movie_lens_online.models import Movie

#Movie.objects.all().delete()

def import_movies(apps, schema_editor):
    Movie = apps.get_model("movie_lens_online", "Movie")

    with open ('/Users/David/documents/django-movies/django-movies/Data/u.item', encoding='latin_1') as movie_file:

        movie_dataset = csv.DictReader(movie_file, fieldnames=('movie_id', 'movie_title', 'release_date'), delimiter="|")

        for row in movie_dataset:

            cln_date = datetime.datetime.strptime(row['release_date'], "%d-%b-%Y").date()

            movie_row = Movie(movie_id=row['movie_id'], movie_title=row['movie_title'], release_date=cln_date) #action=row['action']
            movie_row.save()



class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0004_auto_20160506_0140'),
    ]

    operations = [
        migrations.RunPython(import_movies)
    ]
