# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 04:37
from __future__ import unicode_literals

from django.db import migrations

from movie_lens_online.models import Rater,  Movie,  Rating


from django.db.models import Avg


def get_ave_movie(apps, schema_editor):

    Rating = apps.get_model("movie_lens_online", "Rating")

    Movie = apps.get_model("movie_lens_online", "Movie")
    #Rater = apps.get_model("movie_lens_online", "Rater")

    for movie in Movie.objects.values():

        mov = Movie.objects.get(movie_id= movie['movie_id'])

        rating = Rating.objects.filter(movie_id=movie['movie_id']).aggregate(Avg('rating'))

        mov.avg_rating = (rating['rating__avg'])

        mov.save()




class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0006_auto_20160506_0225'),
    ]

    operations = [
        migrations.RunPython(get_ave_movie)
    ]
